/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <stm32f401re_gpio.h>
#include <led.h>
#include <button.h>
// #if !defined(__SOFT_FP__) && defined(__ARM_FP)
//   #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
// #endif

void mainInit();

int main(void)
{
  mainInit();
  while (1){
    if(GPIO_ReadInputDataBit(GPIOB, GPIO_Pin_3)==0){
      LedControl_SetColorIndividual(LED_KIT_ID0, LED_COLOR_RED, 0);
      LedControl_SetColorIndividual(LED_KIT_ID0, LED_COLOR_GREEN, 100);
    }
    else{
      LedControl_SetColorIndividual(LED_KIT_ID0, LED_COLOR_GREEN, 0);
      LedControl_SetColorIndividual(LED_KIT_ID0, LED_COLOR_RED, 100);
    }
  }
}

void mainInit(){
  SystemCoreClockUpdate();
  LedControl_Init();
  Button_Init();
}

